name: Ubuntu
on: 
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:

      matrix:
        include:
          # 5.12.12
          - qt_version: 5.12.12
            qt_arch: gcc_64
          # 6.9.1
          - qt_version: 6.9.1
            qt_arch: linux_gcc_64
            modules: 'qthttpserver qtwebsockets'
    env:
      BUILD_TYPE: Release
      BUILD_PATH: build
      assume: --release
      qt_target: 'desktop'
      qt_host: 'linux'
      archiveName: 'QOpenAI-${{ matrix.qt_version }}-${{ matrix.qt_arch }}'

    steps:
      # Install Qt
      - name: Install Qt
        if: 'true'

        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ matrix.qt_version }}
          host: ${{ env.qt_host }}
          target: ${{ env.qt_target }}
          arch: ${{ matrix.qt_arch }}
          install-deps: 'true'
          cache: 'true'
          aqtversion: '==3.1.*'
          modules: ${{ matrix.modules }}
          # tools: ${{ matrix.tools }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: CMake Build
        id: build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_INSTALL_PREFIX=${{ env.BUILD_PATH }}/${{ env.BUILD_TYPE }} -B ${{ env.BUILD_PATH }}
          ls

      # CMake Install
      - name: CMake Install
        env:
          prefix: ${{ github.workspace }}
        run: |
          cd ${{ github.workspace }}
          cmake --build ${{ env.BUILD_PATH }} --config ${{ env.BUILD_TYPE }} -j
          ls